### ISSUE TITLE
RegisteredNativeSymbol for toeplitz

### ISSUE THREAD

**Issue by ghost** [chrisvwn/Rnightlights#1]
Hi, 

I tried to follow the example from [this site](http://isharadata.blogspot.com/2017/09/rnightlights-satellite-nightlight-data.html), but once I try to load the library, I get this warning:

`failed to assign RegisteredNativeSymbol for toeplitz to toeplitz since toeplitz is already defined in the ‘spam’ namespace `

It does not let me do anything afterwards. ¿Any advice?

**Comment by chrisvwn** [comment]
Hi @VictorPPB ,

Thanks for reaching out. At what point do you receive that error? Could you run the lines one at a time and post the last line before the error occurs as well as the error?

**Comment by chrisvwn** [comment]
@VictorPPB I'll close this issue since I haven't heard back. Please re-open if it happens again.
