### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by gisavio** [chrisvwn/Rnightlights#17]
Hi Chris,

Just two questions on the program. I am using DMSP-OLS data. What does the program when two satellites are available for the same year? Apparently, it takes the information from the newer one, kindly confirm. Another question: I am trying to get standard deviation of lights (not only sum and mean, which are given by default), but I am not able to get these.

Most thanks for your help, best regards,
Giovanni

**Comment by chrisvwn** [comment]
Hi @gisavio ,

On DMSP-OLS, if we have 2 satellites we are choosing the first satellite. This is not ideal and I have had it in the pipeline for a while now to include data from both satellites. I haven't gotten round to it but will eventually.

Concerning calculating standard deviation, note that you can calculate **any** function; sum and mean are just the ones we do by default. You can calc standard deviation by adding `list("sd", na.rm=T)` to the nlStats list. Note that you can pass in any function even one you have written yourself as long as it takes in a vector and returns a scalar.

**Comment by gisavio** [comment]
Many thanks Chris for the clear and prompt answers, best regards, Giovanni
