### ISSUE TITLE
Unable to download DMSP/OLS for the year 2012.

### ISSUE THREAD

**Issue by nikosGeography** [chrisvwn/Rnightlights#19]
Hi and congrats for the great package.
I want to download just 1 raster of the DMSP/OLS for the year 2012. As I read in the documentation I only have to set the year but I am getting the following error:
**2019-01-07 19:46:09: Downloading 
Error in utils::download.file(ntLtsFileUrl, ntLtsZipLocalNamePathOLS,  : 
'url' must be a length-one character vector**
I would like to ask if this is because of NOAA's site does not work at the moment or if it is because of me.
My code is:
**if(Rnightlights:::downloadNlTilesOLS("2012"))**
  print("download successful")**

Thank you for your time.

**Comment by chrisvwn** [comment]
Hi,

Thank you. I am glad you are finding the package useful.

The error is because the NOAA site is down at the moment.
