### ISSUE TITLE
Cannot open data source in getCtryNlData function

### ISSUE THREAD

**Issue by nreguera** [chrisvwn/Rnightlights#24]
Hi Chris,

I am trying to reproduce the example in your blog, but I got an error message:

> 2019-02-27 10:30:08: NlRange autodetected nlType: VIIRS.M
> Error in rgdal::ogrListLayers(dsn = path.expand(path = getPolyFnamePath(ctryCode = ctryCodes,  : 
>   Cannot open data source

I attach you a screenshot where you can see the few lines I input when got the message.

Thanks.

![screenshot](https://user-images.githubusercontent.com/8281704/53480622-db87a880-3a7b-11e9-8e3c-86e129633232.png)

**Comment by chrisvwn** [comment]
Hi,

This sounds like a possible download error.

Could you delete all files and folder with "KEN" in the name in the polygons folder in your data directory?

Then rerun for the download of polygons to repeat.

**Comment by nreguera** [comment]
So, this is what I did:

- I couldn´t see anything in the data folder (/.Rnightlights/data), and the message kept arising.

- I tried with another country (MMR), and it worked almost until the end, where I got another error. You can see this error attaced.

- Then I tried again with KEN, and it worked, but happened the same as previously with MMR. If you want I can open another wire for this, as it looks a different issue.

![screenshot](https://user-images.githubusercontent.com/8281704/53483726-6a97bf00-3a82-11e9-8646-2081ef0d47b7.png)

**Comment by nreguera** [comment]
Btw, after the two previous loads (MMR and KEN) in the data folder only appears one file (NL_STRUCT_MMR_GADM-3.6)

**Comment by chrisvwn** [comment]
This looks like the problem related to downloading the tile:
![screenshot from 2019-02-27 13-56-54](https://user-images.githubusercontent.com/6387770/53485648-ccaeef00-3a97-11e9-88a7-0bbd5fb34f06.png)

This is the kind of output we are expecting:
![screenshot from 2019-02-27 14-01-27](https://user-images.githubusercontent.com/6387770/53485838-4d6deb00-3a98-11e9-9af0-38e9184f039d.png)

Is it possible the downloads are being interrupted?

**Comment by nreguera** [comment]
Mmm I deleted all the files and tried again, but I still get the same messages (the ones you pointed out). 

I am in a public wireless hotspot but the connection is quite good... 

Should I remove all the files related to the countries and try again?

**Comment by chrisvwn** [comment]
Hmm. Could they be restricting large downloads? Try downloading the tile directly e.g. try this [https://data.ngdc.noaa.gov/instruments/remote-sensing/passive/spectrometers-radiometers/imaging/viirs/dnb_composites/v10//201204/vcmcfg/SVDNB_npp_20120401-20120430_75N060W_vcmcfg_v10_c201605121456.tgz](https://data.ngdc.noaa.gov/instruments/remote-sensing/passive/spectrometers-radiometers/imaging/viirs/dnb_composites/v10//201204/vcmcfg/SVDNB_npp_20120401-20120430_75N060W_vcmcfg_v10_c201605121456.tgz)

**Comment by nreguera** [comment]
Don´t thing so, I have downloaded virtual machines of 3/4 Gbs... 

I have reset and deleted all data, even in R session, and now it looks it´s downloading properly, despite a bit slow. Wait until it finish and I will let you know.

![screenshot](https://user-images.githubusercontent.com/8281704/53486714-c9ad0200-3a89-11e9-90a5-db5906992d97.png)

**Comment by chrisvwn** [comment]
Okay. Yes. This looks positive. If the download completes fine it should run successfully.

If you want faster downloads you can experiment with the `aria2` option by installing [https://aria2.github.io/](https://aria2.github.io/) and setting `pkgOptions(downloadMethod="aria")`

**Comment by nreguera** [comment]
Hi Chris,

Yesterday I had to interrupt the download because I needed to leave, and now I am getting the same problems. What should I clean to restart the download?

**Comment by chrisvwn** [comment]
Hi Natxo,

Delete the .tif and/or .tgz files corresponding to the interrupted download in the tiles folder.

**Comment by nreguera** [comment]
Ok, it was working until the internet connection fell down, so I need to restart right? It would be nice to be able to continue the download where it was cut...

**Comment by chrisvwn** [comment]
Noted. The aria option has this capability but it is a bit more complex when using the default R downloader.

**Comment by nreguera** [comment]
I am going to try with aria. I just downloaded it, and I am wondering if I need to install it or set it up to use it with Rnightlights package...

**Comment by chrisvwn** [comment]
Just install it and ensure you can access it globally by running aria2c from the commandline. (If it is not accessible after install, you can add the installation folder to the `PATH` environment variable). Then run `pkgOptions(downloadMethod='aria')` before running `getCtryNlData`.

**Comment by nreguera** [comment]
Thanks for your support Chris, I think we can close this issue and move on.
