### ISSUE TITLE
Moonlight, fires, and other natural sources of light

### ISSUE THREAD

**Issue by nreguera** [chrisvwn/Rnightlights#26]
Hello Chris,

I am wondering if the data available through the package could be linked to the corrections that Miguel Román and his team did over the VIIRS data (you can read about this here [https://earthobservatory.nasa.gov/images/90008/night-light-maps-open-up-new-applications]).

Thanks

**Comment by chrisvwn** [comment]
Hi Natxo,

This is one of the future features of the package. It currently does not
remove the known lights sources. For many countries it won't be a problem
but countries with oil drilling, wildfires, volcanoes will be affected.
However, if I remember well, there is one of the nightlights datasets that
already has that correction applied. Let me do a check and get back to you.

**Comment by chrisvwn** [comment]
Hi Natxo,

Sorry for taking so long to get back to you.

So, I was not quite correct. The nightlights datasets that have fire and
ephemeral lights removed are in the VIIRS.Y dataset. Flares, fires, etc
averaged annually are used to remove these lights. None of the VIIRS.M
files has this.

Please see this page for details on the various VIIRS files and what they
contain (https://www.ngdc.noaa.gov/eog/viirs/download_dnb_composites.html).
You can choose the appropriate file to use in the package by setting the
pkgOptions("configName.VIIRS.D/M/Y") option. Run ?Rnightlights::pkgOptions
to see the corresponding options and available values.

For more information on fires, flares, etc you might want to look at this
page: https://ngdc.noaa.gov/eog/viirs/download_viirs_fire.html.
This document gives some procedure to process nightlights including gas
flare removal:
http://darrylmcleod.com/wp-content/uploads/2016/06/Night-Lights-and-ArcGIS-A-Brief-Guide.pdf

I will be adding this option in a future release.

**Comment by nreguera** [comment]
Hello Chris,

Thank you for the information. I will be attentive to the release.

**Comment by effi425xiao** [comment]
Hi Chris,
I am only interested in Gas Flares and how you get only these signals removed, do you have a layer for that?
Xiao

**Comment by chrisvwn** [comment]
Hi,

I do not have the layer for VIIRS. For OLS you can get the polygons here:

[https://ngdc.noaa.gov/eog/interest/gas_flares_countries_shapefiles.html](https://ngdc.noaa.gov/eog/interest/gas_flares_countries_shapefiles.html)

However, I am not sure about how up-to-date they are.

**Comment by effi425xiao** [comment]
Thanks for the reply, I checked this data yesterday, it didn't cover the
flares I could see in some areas. I am curious if you know of the
processing code on VNF, for gas flare?
Xiao

**Comment by chrisvwn** [comment]
Unfortunately, no. This is one of the tasks I need to complete to put this package back up on CRAN. But haven't had the time as of yet.
