### ISSUE TITLE
Available periods

### ISSUE THREAD

**Issue by nreguera** [chrisvwn/Rnightlights#27]
Hi Chris,

I am trying to figure out if I have available monthly periods from 2012 to 2018 using the code:

`validNlPeriods(c("201201", "201812"),"VIIRS.M")`
--> Get FALSE, so I understand I don´t

Thanks.

Natxo.

**Comment by nreguera** [comment]
Ok, found it:

`getAllNlPeriods("VIIRS.M")`

The code from the previous comment I understand it's for specific periods, so because the data it's only available from 201204 I got FALSE.

**Comment by chrisvwn** [comment]
Exactly!

**Comment by nreguera** [comment]
Good help documentation anyway :)
