### ISSUE TITLE
Tiles: how to stop downloading them

### ISSUE THREAD

**Issue by nreguera** [chrisvwn/Rnightlights#29]
Hi Chris,

I think I have seen it but I can´t find it. Is there a parameter that allows stop downloading the tiles? If not, do I need to delete them manually or is there any parameter that do that automatically?

Thanks.

Natxo.

**Comment by chrisvwn** [comment]
Hi Natxo,

Could you clarify what you mean by "stop downloading the tiles"?

Chris

**Comment by nreguera** [comment]
I mean those TIFF images that weight 1.93GB each in the tiles folder. I am downloading the whole monthly time series for a country and it takes a lot of time and it's filling my disk. So I want to know first if I can download only the data without these pictures, and if I can not, if there is a way to delete them automatically after download. Despite this second option it's easy to do it manually, it will allow me to download the whole monthly series for several countries without worrying to delete them, cause my hard drive is not very big.

Thanks!

Natxo.

**Comment by chrisvwn** [comment]
Thanks for clarifying. Yes, the rasters are very large. To have them deleted automatically run `pkgOptions(deleteTiles=TRUE)` before running `getCtryNlData` or `processNlData`.

Chris

**Comment by nreguera** [comment]
Ah yes! I saw it somewhere but could not remember it. Thanks again Chris.
