### ISSUE TITLE
Error message after reinstalling R

### ISSUE THREAD

**Issue by nreguera** [chrisvwn/Rnightlights#30]
Hi Chris:

I am having troubles with my S.O. and I have been reinstalling R Studio several times. Now when I try to restart the NightLights downloads where I left them, I got the following error message:

```
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file. (file does not exist)
```

Any idea?

Thanks.

Natxo.

**Comment by nreguera** [comment]
A screenshot just in case helps:

![screenshot](https://user-images.githubusercontent.com/8281704/55572558-24302280-5708-11e9-86cb-4e890a05e0bb.png)

The data I am trying to download is the one that relates to year 2016 month 12.

**Comment by chrisvwn** [comment]
Hi Natxo,

Looks like the download did not complete. So what happens if the download is interrupted and the package thinks it completed it will decompress it and end up with an invalid raster but the package still thinks it is okay so it will not resume the download the next time.

In this case, try deleting the tile and trying again.

Chris

**Comment by nreguera** [comment]
I already tried that, I remove the tiles in the tiles folder, and checked that no other reference is in other folder (i.e. outputrasters,...)

**Comment by chrisvwn** [comment]
Hmm. That's strange. Are you using aria2 to download? Are you getting an error when downloading?

**Comment by nreguera** [comment]
Sorry Chris! My mistake, I created a PATH environmental variable in my user variables instead of using the one already that exists in the system variables. So I deleted the aria2 folder location in the first and added in the system and now looks it's working again.

Thanks!

**Comment by nreguera** [comment]
Sorry Chris! My mistake, I created a PATH environmental variable for aria2 in my user variables instead of using the one that already exists in the system variables. So I deleted the aria2 folder location in the first and added in the system and now looks it's working again.

Thanks!
