### ISSUE TITLE
Tile not available on the NOAA page

### ISSUE THREAD

**Issue by nreguera** [chrisvwn/Rnightlights#31]
Hi Chris:

I am resuming a download (year 2018 month 6 for Cambodia) and I got this error:

![screenshot](https://user-images.githubusercontent.com/8281704/55741457-8ef59c80-5a2d-11e9-9254-dbebaa53a03c.png)

I have checked that the folders "tiles" and "outputrasters" don´t have anything related to this data, and tried several times, but I still get the error. Any idea?

Thanks. 

Natxo.

**Comment by chrisvwn** [comment]
Hi Natxo,

It seems that the monthly VIIRS tile for 201806 does not exist.

I had written to the guys over at NOAA about this but haven't got a response as yet.

Regards,

Chris

**Comment by chrisvwn** [comment]
Hi,

An update on this issue. The guys at NOAA are looking into this and will get back as soon as they can.

Chris

**Comment by nreguera** [comment]
Thanks for the update Chris.

**Comment by chrisvwn** [comment]
I believe this issue was resolved as the tile is now available. Closing this issue.
