### ISSUE TITLE
Error in seq.int

### ISSUE THREAD

**Issue by DAMON10780** [chrisvwn/Rnightlights#32]
Hi Chris,
highestAdmLevelStats <- getCtryNlData(ctryCode = ctry, 
                                      admLevel = "highest",
                                      nlType = "VIIRS.M", 
                                      nlPeriods = nlRange("201401", "201412","VIIRS.M"), 
                                      nlStats = list("sum",na.rm=TRUE),
                                      ignoreMissing=FALSE)
I have encountered such an error message:Error in seq.int(r1$mon, 12 * (to0$year - r1$year) + to0$mon, by) :  'to' must be a finite number

**Comment by chrisvwn** [comment]
Hi @chrisvwn,

This looks like it is related to the locale on your computer. Please see this issue #8.

Try running `Sys.setlocale("LC_TIME", "English")`.

Chris

**Comment by chrisvwn** [comment]
Closing this issue. Please reopen if you still face the same issue.
