### ISSUE TITLE
cannot open URL 'https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_KEN_shp.zip'

### ISSUE THREAD

**Issue by RegisKouassi** [chrisvwn/Rnightlights#39]
Hi Chris, thanks for this package which simplifies the gathering of nightlights data. but I have got a message error when trying to replicate the example provided in the package description; below a picture of what I get: 
![image](https://user-images.githubusercontent.com/48491209/66261871-01f48b80-e7a3-11e9-9ba5-72afcf2b147d.png)

**Comment by chrisvwn** [comment]
Hi @RegisKouassi ,

It seems the GADM site which we use as our source of country polygons is down. This should be a temporary problem. Please try again later or during the week.

**Comment by RegisKouassi** [comment]
Thanks, Chris, for your quick reply about this subject.
I will try again by the end of the week.

**Comment by chrisvwn** [comment]
Great! I have tested a download and it worked so you should be fine. Closing the issue.

**Comment by FaezeMnr** [comment]
Hi Chris and I hope you are well.
Thank you so much for this great package. I have the same problem, and it seems that the "https://biogeo.ucdavis.edu/" website is run into some problems. Could you please help me to solve this?

**Comment by petricmina9** [comment]
same, tried yesterday evening and today, server seems to be down

**Comment by chrisvwn** [comment]
It does seem that their server is down. Unfortunately, that is beyond my control. You could try requesting assistance/reporting the issue via their contact form at [http://rasterra.com/contact/gadm_contact_form](http://rasterra.com/contact/gadm_contact_form)

**Comment by petricmina9** [comment]
Thnx @@chrisvwn, I sent a message describing the issue through the form you provided

**Comment by chrisvwn** [comment]
I have just had a look and it seems the site is back up. Kudos for reporting! Seems they acted on it.

**Comment by FaezeMnr** [comment]
Thanks, @chrisvwn. Yes, it is working now.
