### ISSUE TITLE
Data from Myanmar?

### ISSUE THREAD

**Issue by nreguera** [chrisvwn/Rnightlights#42]
Hi Chris,

Can you check if the data for Myanmar corresponding to October 2013 exists? I have downloaded all the periods and this doesn´t appears, and when I try to download again it tells me that all stats exists.

![screenshot](https://user-images.githubusercontent.com/8281704/67614266-d3853180-f7df-11e9-87a5-e033d7aa3699.png)

Thanks.

**Comment by nreguera** [comment]
Just reviewing the folder where the data is stored, I found two files: 

- NL_DATA_MMR_ADM3_GADM-3.6-SHPZIP
- NL_DATA_MMR_ADM3_GADM-3.6

The first one contains columns with this name `NL_VIIRS.M_VCMCFG-MTSALL-MEAN-RGFT_201408_SUM` and the second one with this one `NL_VIIRS.M_201408_SUM`.

The first one contains all the readings, the second one apart from the file I told you, it has only until 201411. I have downloaded previously the data for Cambodia and used the second type of file. What are the differences among them?

**Comment by chrisvwn** [comment]
Hi Natxo,

Which version of Rnightlights are you using? The different data filenames indicate a version update at some point but the `-SHPZIP` should be the latest in use and the old filename should have been renamed. All the same, the `-SHPZIP` is probably the one in use unless the package was downgraded again.

**Comment by nreguera** [comment]
I think I was using the last one (I had to reinstall everything so I can´t remember). So may I just keep the data files that end with `-SHPZIP` then?

**Comment by chrisvwn** [comment]
Yes, you can just keep the `-SHPZIP` only.

**Comment by chrisvwn** [comment]
Closing this issue. Please reopen if you are still having a problem.
