### ISSUE TITLE
Using Rnightlights with RStudio Coud

### ISSUE THREAD

**Issue by nreguera** [chrisvwn/Rnightlights#43]
Hi Chris,

I am trying to use RStudio cloud but when I try to install the library it gives me the error that is not available for the version (3.6.0 and 3.5.3, I have tried with both). Is there a way to run it over the cloud?

Thanks.

**Comment by chrisvwn** [comment]
Hi Natxo,

I have taken the package offline for review after some issues were raised. I am hoping to have it back up in a couple of weeks. Meanwhile you can install the latest version from the archive like so:
```
packageurl <- "https://cran.r-project.org/src/contrib/Archive/Rnightlights/Rnightlights_0.2.4.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

**Comment by nreguera** [comment]
Does it affect as well to local RStudio? I had to reinstall everything in my laptop, and now when I try to install Rnightlights package I get this error message:

![Untitled](https://user-images.githubusercontent.com/8281704/68065140-0a64c580-fd53-11e9-8f0f-4871dd24df66.png)

I am using RStudio 1.1.463 and R 3.6.1

**Comment by nreguera** [comment]
I managed to install the dependencies separatelly, and it looks its working. But now, when I try to download the data, it gives me the following error:

![Untitled](https://user-images.githubusercontent.com/8281704/68079930-4580fa80-fe20-11e9-94bb-55aa720b538d.png)

**Comment by nreguera** [comment]
Never mind, I just tried again and it worked. No idea why, as I didn´t change anything. Thanks anyway.

**Comment by chrisvwn** [comment]
Nice that you were able to solve this. Most likely a temporary network issue.
