### ISSUE TITLE
Installing in version 3.6.1

### ISSUE THREAD

**Issue by ludelgad** [chrisvwn/Rnightlights#44]
I´m getting the following message when trying to install in Mac OS X Rnightlights package:

Warning in install.packages :
  package ‘Rnightlights’ is not available (for R version 3.6.1)

Trying to install it manually but couldn´t do it.
Thanks

**Comment by chrisvwn** [comment]
Hi @ludelgad,

The package is currently down for review. You can install it from the archive using the following command:
```
packageurl <- "https://cran.r-project.org/src/contrib/Archive/Rnightlights/Rnightlights_0.2.4.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```
If this does not work. Try installing the dependencies first as they are listed

**Comment by ludelgad** [comment]
Thanks for the fast reply @chrisvwn . I already tried and it appears the following error:

ERROR: dependencies ‘cleangeo’, ‘curl’, ‘data.table’, ‘doSNOW’, ‘dplyr’, ‘ff’, ‘ffbase’, ‘foreach’, ‘lubridate’, ‘raster’, ‘readr’, ‘reshape2’, ‘rgdal’, ‘rgeos’, ‘R.utils’, ‘rvest’, ‘rworldmap’, ‘settings’, ‘snow’, ‘sp’, ‘stringr’, ‘xml2’ are not available for package ‘Rnightlights’

How I should proceed?

Thanks!

**Comment by chrisvwn** [comment]
You can install the dependencies first i.e. 

```
install.packages(c('cleangeo', 'curl', 'data.table', 'doSNOW', 'plyr', 'ff', 'ffbase', 'foreach', 'lubridate', 'raster', 'readr', 'reshape2', 'rgdal', 'rgeos', 'R.utils', 'rvest', 'rworldmap', 'settings', 'snow', 'sp', 'stringr', 'xml2'))

packageurl <- "https://cran.r-project.org/src/contrib/Archive/Rnightlights/Rnightlights_0.2.4.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```

**Comment by chrisvwn** [comment]
Closing this issue. Please reopen if you are still encountering a problem.

**Comment by pk1196** [comment]
hi, I am encountering the same issue and tried installing the dependencies first by pasting your command above but was prompted to key in some additional info ("+" sign appears). would really appreciate your help with this, thank you!

**Comment by chrisvwn** [comment]
Okay. When I copy-pasted the command it changed the single quotes to some
other character. Please try it again. I have pasted it here for convenience:

```

install.packages(c('cleangeo', 'curl', 'data.table', 'doSNOW', 'plyr',
'ff', 'ffbase', 'foreach', 'lubridate', 'raster', 'readr', 'reshape2',
'rgdal', 'rgeos', 'R.utils', 'rvest', 'rworldmap', 'settings', 'snow',
'sp', 'stringr', 'xml2'))

packageurl <- "https://cran.r-project.org/src/contrib/Archive/Rnightlights/Rnightlights_0.2.4.tar.gz"
install.packages(packageurl, repos=NULL, type="source")
```
