### ISSUE TITLE
Defaults for ntLtsIndexUrlVIIRS.M and ntLtsIndexUrlVIIRS.Y

### ISSUE THREAD

**Issue by memoryfull** [chrisvwn/Rnightlights#59]
Hello.

Defaults for `ntLtsIndexUrlVIIRS.M`, `ntLtsIndexUrlVIIRS.Y` in [options.R](https://github.com/chrisvwn/Rnightlights/blob/bba65d347001dbde677b00417775d7cb421921b3/R/options.R#L102) are currently set to `https://eogdata.mines.edu/download_dnb_composites_iframe.html`. This webpage states:

> Last Update: 09/10/2019/12:02:31

In contrast, `https://eogdata.mines.edu/pages/download_dnb_composites_iframe.html` states:

> Last Update: 02/13/2020/15:40:50 

I suggest replacing the existing URLs with the updated ones.

**Comment by chrisvwn** [comment]
Thanks @memoryfull! Let me review for inclusion. I actually thought I had made the change already.

**Comment by chrisvwn** [comment]
@memoryfull You were right. Made the changes. Thank you!
