### ISSUE TITLE
Using custPolyPath to download radiance using different administrative divisions

### ISSUE THREAD

**Issue by nreguera** [chrisvwn/Rnightlights#67]
Hi Chris.

I am trying to download the radiances using the following geographical layers instead of the preset GADM:

- [Myanmar National Boundary MIMU v9.2.1](http://geonode.themimu.info/layers/geonode%3Ammr_polbnda_adm0_250k_mimu)
- [Myanmar State and Region Boundaries MIMU v9.2.2](http://geonode.themimu.info/layers/geonode%3Ammr_polbnda_250k_adm1_mimu)
- [Myanmar Township Boundaries MIMU v9.2.4](http://geonode.themimu.info/layers/geonode%3Ammr_polbnda_250k_adm3_mimu)

The formats of files available for the layers are the following ones:

![image](https://user-images.githubusercontent.com/8281704/101298398-27c06900-385c-11eb-8ab8-85eb62dc756c.png)

I choose the shapefile format. This format contains the following files (same for each division admin0, admin1 and admin3, in the next screenshot showing the ones in the admin3 level):

![image](https://user-images.githubusercontent.com/8281704/101298348-f5167080-385b-11eb-9e80-c3c9188ad0e9.png)

In R (version 4.0.2) with Rstudio (version 1.4.904) and Rnightlights (version 0.2.4.5), I run this code to download the nightlights data:

![image](https://user-images.githubusercontent.com/8281704/101298530-d06ec880-385c-11eb-88da-967133ba9a68.png)

having the custPolyPath file needed to crop the rasters in that folder that you can see in the previous screenshot (and in the same folder where all the other admin levels files are). This compressed file contains all the files I showed you previously, I haven´t modified it. 

After running it, this is the ouptut and the error that I get:

![image](https://user-images.githubusercontent.com/8281704/101298822-27c16880-385e-11eb-8485-a7b5b0c14b72.png)

After the previous process finishes, there are these new files in a local folder created by the process:

![image](https://user-images.githubusercontent.com/8281704/101298866-54758000-385e-11eb-80cc-a1148789ac32.png)

and inside the **POLY_MMR_CUST-mmr_polbnda_250k_adm3_mimu.zip-SHPZIP** folder there are these files:

![image](https://user-images.githubusercontent.com/8281704/101298906-84bd1e80-385e-11eb-84b6-4681f278ee52.png)

It seems that it fails to create the CSV file structure to store the radiances right?

Thanks.

**Comment by chrisvwn** [comment]
Hi Natxo,

Thank you for trying out the custPolyPath feature and for the detail in this issue.

Yes, it seems to have gone most of the way but is unable to create the CSV file structure.

Let me try it here and get back to you.

**Comment by chrisvwn** [comment]
Seems the package was able to import it. I used `getCtryNlData()` so the error at the end is because I used the wrong `admLevel` which is the same layer name since it is difficult to determine the actual name.

See below:
![image](https://user-images.githubusercontent.com/6387770/101329872-fe670380-3882-11eb-931c-e114505bd53a.png)
![image](https://user-images.githubusercontent.com/6387770/101329891-04f57b00-3883-11eb-9c4c-dcc0d1ecfad2.png)

Verifying the structure has been imported:
```
> Rnightlights:::readCtryStruct("MMR", custPolyPath = "mmr_polbnda_250k_adm3_mimu.zip")
     0_mmr_polbnda_250k_adm3_mimu area_sq_km
  1:                       Ramree   1170.124
  2:                      Toungup   4792.945
  3:                     Kyaukpyu   1168.149
  4:                      Labutta   2492.103
  5:                     Ngapudaw   3210.414
 ---                                        
326:                       Laihka   2797.747
327:                    Mongkaing   3779.654
328:                        Hseni   1241.766
329:                      Kunlong   1174.341
330:                         Muse   1981.160
```
Looking at the error again, it seems it is a failure to write the file due to some filesystem issue- either it was unable to create the file or the directory did not exist. Not sure what is going on there. Could you try again? If it still doesn't work try deleting the `NL_STRUCT_MMR_CUST-mmr_polbnda_250k_adm3_mimu.zip-SHPZIP.csv` file and try again.

**Comment by nreguera** [comment]
So a couple of things here:

- Just realizing that after installing Rnightlights package it didn´t ask me for the path.
- Looking at the folder that the process used, it only contains these folders:

![image](https://user-images.githubusercontent.com/8281704/101421665-39b90f00-3923-11eb-8abc-d495f5c0774b.png)

- After manually launching the process _setupDataPath_, I got these ones:

![image](https://user-images.githubusercontent.com/8281704/101421731-679e5380-3923-11eb-90b6-1d663ccf2a4d.png)

Maybe the error came from that reason?

- I relaunched the process, and I get this error:

![image](https://user-images.githubusercontent.com/8281704/101421786-8997d600-3923-11eb-905f-e9fb650727c9.png)

After this, I do have the CSV file structre created in the _data_ folder, and in the _polygons_ folder I have the same files I told you previously.

**Comment by chrisvwn** [comment]
Yes, that sounds like the problem. For some reason the data directory was not created first time round at installation. I am not sure what might have happened there but glad it worked when you run setupDataPath manually. If this happens again let me know so I can try to track down the problem.

For the admLevel you can run the following to list all admLevels in the polygon:
```
searchAdmLevel(ctryCode = "MMR", custPolyPath = "mmr_polbnda_250k_adm3_mimu.zip")
```

Note that to access this particular polygon you must specify the ctryCode and custPolyPath together. For custPolyPath we only look at the filename so you don't have to specify the full path subsequently. This also means that even if you use a custPolyPath with a different path but same filename it will think this is the same one as before.

**Comment by nreguera** [comment]
So I run that code only once before _getCtryNlData_?

When you said that I must specify the ctryCode and custPolyPath together, do you mean in the _getCtryNlData_ function?

So I tried again with this code:

```
searchAdmLevel(ctryCode = "MMR", 
               custPolyPath = "mmr_polbnda_250k_adm3_mimu.zip")

# Download rasters (tiff) and radiance readings (csv)
nl_source <- getCtryNlData(
  ctryCode = ctry, # country
  admLevel = "admin3", # admin level
  custPolyPath = "mmr_polbnda_250k_adm3_mimu.zip",
  nlType = "VIIRS.M", # monthly values
  nlPeriods = nlRange("201204", "201212"),
  ignoreMissing = FALSE, # not ignoring missing values
  nlStats = list("mean", na.rm=FALSE) # aggregation: average 
)
```

And I got this error:

![image](https://user-images.githubusercontent.com/8281704/101458760-ae14a200-3965-11eb-9bce-8fb1935eab6d.png)

If I set the full path of in the CustPolyPath parameter I get the same error.

Maybe should I remove all the files and try it again?

**Comment by chrisvwn** [comment]
What I mean is whenever you are referencing this map e.g. `getCtryNlData`, `searchAdmLevel`, and any other function that has `ctryCode` and `custPolyPath` parameters you need to specify both otherwise it will consider it a different request and you may see it try to re-import the polygon or fail to recognize it.

So searchAdmLevel will give you a list of valid admLevels. Unfortunately, for `custPolyPath` we cannot determine the real name at import so we will find it has a different admLevel name. When I run it I get:

```
> Rnightlights::searchAdmLevel(ctryCode = "MMR", custPolyPath = "mmr_polbnda_250k_adm3_mimu.zip")
$mmr_polbnda_250k_adm3_mimu.zip
$mmr_polbnda_250k_adm3_mimu.zip$MMR
[1] "0_mmr_polbnda_250k_adm3_mimu"
```

This shows there is only 1 admLevel and it is assigned the name `"0_mmr_polbnda_250k_adm3_mimu"`. So this is the admLevel you use in getCtryNlData, not "admin3".

**Comment by nreguera** [comment]
Does _searchAdmLevel_ does create the CSV as well? And when using _custPolyPath_ we still need to set the `admLevel `right?

I have run this code:

```
nl_source <- getCtryNlData(
  ctryCode = ctry, # country
  custPolyPath = "mmr_polbnda_250k_adm3_mimu.zip",
  admLevel = "0_mmr_polbnda_250k_adm3_mimu", # admin level
  nlType = "VIIRS.M", # monthly values
  nlPeriods = nlRange("201204", "201212"),
  ignoreMissing = FALSE, # not ignoring missing values
  nlStats = list("mean", na.rm=FALSE) # aggregation: average 
)
```

and I get this output with an error:

![image](https://user-images.githubusercontent.com/8281704/101558163-cd0a4700-39ec-11eb-9eb0-b6a2fb0ce608.png)

I do have the _NL_STRUCT_MMR_CUST-mmr_polbnda_250k_adm3_mimu.zip-SHPZIP.csv_ file in _E:/R/.Rnightlights/data_ and I can open it. It looks fine for me. I attach it here.

[NL_STRUCT_MMR_CUST-mmr_polbnda_250k_adm3_mimu.zip-SHPZIP.zip](https://github.com/chrisvwn/Rnightlights/files/5662792/NL_STRUCT_MMR_CUST-mmr_polbnda_250k_adm3_mimu.zip-SHPZIP.zip)

**Comment by chrisvwn** [comment]
So the main error here I think is `something went wrong with tile downloads`.

It seems the download site now requires registration and login. [https://payneinstitute.mines.edu/eog-2/transition-to-secured-data-access/](https://payneinstitute.mines.edu/eog-2/transition-to-secured-data-access/)

The second error is because the data file has not been created yet due to the first error. Note the file it is complaining about is not `NL_STRUCT_...` it is `NL_DATA_...`.

Let me see if I can quickly add the auth required.

**Comment by chrisvwn** [comment]
Hi @nreguera ,

I have been able to add a preliminary authorization bit. Could you give it a go?

You can update the package and try again.

**Comment by nreguera** [comment]
Hi Chris,

This is what I get when trying to download them:

![image](https://user-images.githubusercontent.com/8281704/101869022-eb1ea580-3bac-11eb-8fda-10d72c28fd7b.png)


Should we create our own credentials or it will be managed through the package?

**Comment by chrisvwn** [comment]
Hi,

You need to register individually at [https://eogauth.mines.edu/auth/realms/master/account/](https://eogauth.mines.edu/auth/realms/master/account/) then enter the credentials in the package. The credentials will be saved in the .Rnightlights folder for future use so you only need to do this once.

**Comment by nreguera** [comment]
OK, done, but I got this error:

![image](https://user-images.githubusercontent.com/8281704/101869787-a7c53680-3bae-11eb-815a-c68f6990a160.png)

**Comment by chrisvwn** [comment]
Not sure what happened there. Could you try again now that the credentials are saved?

**Comment by nreguera** [comment]
Just tried again, same error, but it doesn´t ask for the credentials

**Comment by nreguera** [comment]
ok, wait, I just restarted the session and it looks working. hold on because i forgot to install aria2 :) I will write you later

**Comment by nreguera** [comment]
I think it's working now 👍 Let´s close this issue and if I see any other thing when using them we can reopen it again.

Thanks for your support Chris 🙏🏻

**Comment by chrisvwn** [comment]
You're welcome
