### ISSUE TITLE
HTTP status was '401 Unauthorized'-Tile Downloading

### ISSUE THREAD

**Issue by naiktejashvi** [chrisvwn/Rnightlights#68]
Hi Chris,

I am facing authentication issue with downloading the tile, is there a way to pass authentication credentials with getCtryNlData function for downloading the data

**Comment by chrisvwn** [comment]
Hi,

Please ensure you are using the latest version of the package from github. Authorization for tile downloads was added recently.

**Comment by naiktejashvi** [comment]
Hi Chris,

Thank you for your immediate response, will install the new version and update you.

**Comment by naiktejashvi** [comment]
Thank you so much, I was able to download the data successfully.

**Comment by chrisvwn** [comment]
Awesome. Thank you for the feedback. As this is a new feature I am glad that you got it to work.
