### ISSUE TITLE
manual download of files into data folder

### ISSUE THREAD

**Issue by alanpaulkwan** [chrisvwn/Rnightlights#69]
Love the package. I have privately cloned/fixed some of the workflow in my own repository as the download function is now impeded by a login. Do you know if

1. It would be possible to automate around this or
2. We can just sign up and download Nightlights data ourselves by hand?

I noticed the data folder has a naming convention that doesn't match those downloads on the site.

**Comment by chrisvwn** [comment]
Thanks! The latest github version caters for this new authentication. You will need to manually register on the download site then supply the creds to the package and it should continue to work as normal.

Yes, the pkg uses an internal naming convention for the tiles which is easier for a layman to understand but there is a disconnect with the original names. Do you feel that having the original filenames would be helpful?

**Comment by alanpaulkwan** [comment]
Happy to close this issue. But on the matter of the internal naming issue, I would say if this issue ever comes up again, having a naming convention similar to that on the site enables a workaround.

If I may, perhaps the unzipped files could have a more human-readable convention?

**Comment by chrisvwn** [comment]
Thanks for the feedback. I will consider this for future releases.
