### ISSUE TITLE
VIIRS Files for 2012 and 2013

### ISSUE THREAD

**Issue by pjpaulpj** [chrisvwn/Rnightlights#7]
Hi Chris,

I noticed that the package only allows the download and processing of files from 2014 January. However on the NOAA website, they [list ](https://ngdc.noaa.gov/eog/viirs/download_dnb_composites.html#NTL_2015) VIIRS files going back to 2012, April. 

Is my understanding correct? Is there a reason for this behaviour?

Regards,

**Comment by chrisvwn** [comment]
Please check that you have the latest versions of the Rnightlights package. v0.2.0 is recently out and v0.1.5 was the previous latest. An earlier version had that issue and it is fixed in later versions.
