### ISSUE TITLE
space management

### ISSUE THREAD

**Issue by alanpaulkwan** [chrisvwn/Rnightlights#70]
Hi, I noticed that the package has extreme space consumption because it retains the .tgz copy and an uncompressed copy. I am wondering if there's an option to just delete the uncompressed copy (knowing it'll add to time).

Alternatively, an ambitious goal would be to re-code the data via another format, such as .fst or parquet, that would enable for fast decompression / efficient compression.

**Comment by chrisvwn** [comment]
Hi. You can run `pkgOptions(deleteTiles=TRUE)` before you run your job.

For existing tiles, you will need to manually delete. I will write functions to help with this.

**Comment by chrisvwn** [comment]
Closing issue. Feel free to reopen if you have further questions.
